CREATE TABLE IF NOT EXISTS assets (
    id                      UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    municipality_id         UUID NOT NULL,
    asset_code              VARCHAR(30) UNIQUE NOT NULL,
    internal_code           VARCHAR(50),
    sbn_code                VARCHAR(50),
    description             VARCHAR(500) NOT NULL,
    category_id             UUID,
    subcategory_id          UUID,
    brand                   VARCHAR(100),
    model                   VARCHAR(100),
    serial_number           VARCHAR(100),
    useful_life             INTEGER,
    asset_plate             VARCHAR(20),
    qr_code                 VARCHAR(100),
    barcode                 VARCHAR(100),
    rfid_tag                VARCHAR(100),
    color                   VARCHAR(50),
    dimensions              VARCHAR(200),
    weight                  DECIMAL(10,3),
    material                VARCHAR(100),
    supplier_id             UUID,
    acquisition_date        DATE NOT NULL,
    acquisition_type        VARCHAR(30) DEFAULT 'PURCHASE',
    invoice_number          VARCHAR(100),
    purchase_order_number   VARCHAR(100),
    pecosa_number           VARCHAR(100),
    acquisition_value       DECIMAL(15,2) NOT NULL,
    currency                VARCHAR(3) DEFAULT 'PEN',
    current_value           DECIMAL(15,2),
    residual_value          DECIMAL(15,2) DEFAULT 0,
    accumulated_depreciation DECIMAL(15,2) DEFAULT 0,
    asset_status            VARCHAR(30) DEFAULT 'AVAILABLE',
    conservation_status     VARCHAR(30) DEFAULT 'GOOD',
    current_location_id     UUID,
    current_responsible_id  UUID,
    current_area_id         UUID,
    entry_date              TIMESTAMP NOT NULL DEFAULT NOW(),
    last_inventory_date     DATE,
    next_depreciation_date  DATE,
    warranty_expiration_date DATE,
    observations            VARCHAR(1000),
    technical_specifications VARCHAR(1000),
    attached_documents      VARCHAR(1000),
    custom_fields           VARCHAR(1000),
    image_url               VARCHAR(500),
    is_inventoriable        BOOLEAN DEFAULT true,
    requires_maintenance    BOOLEAN DEFAULT false,
    is_depreciable          BOOLEAN DEFAULT true,
    created_by              UUID NOT NULL,
    created_at              TIMESTAMP DEFAULT NOW(),
    updated_by              UUID,
    updated_at              TIMESTAMP DEFAULT NOW(),
    version                 INTEGER DEFAULT 1,
    final_user_id           UUID,
    alta_date               DATE,
    alta_doc_type           VARCHAR(30),
    alta_doc_number         VARCHAR(100),
    account_code            VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_assets_patrimonial_code ON assets(asset_code);
CREATE INDEX IF NOT EXISTS idx_assets_asset_status ON assets(asset_status);
CREATE INDEX IF NOT EXISTS idx_assets_category_id ON assets(category_id);

CREATE TABLE IF NOT EXISTS depreciations (
    id                      UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    asset_id                UUID NOT NULL,
    fiscal_year             INTEGER NOT NULL,
    calculation_month       INTEGER NOT NULL,
    initial_value           DECIMAL(15,2) NOT NULL,
    useful_life_years       INTEGER NOT NULL,
    residual_value          DECIMAL(15,2) DEFAULT 0,
    annual_depreciation     DECIMAL(15,2) NOT NULL,
    monthly_depreciation    DECIMAL(15,2) NOT NULL,
    previous_accumulated_depreciation DECIMAL(15,2) DEFAULT 0,
    period_depreciation     DECIMAL(15,2) NOT NULL,
    current_accumulated_depreciation DECIMAL(15,2) NOT NULL,
    previous_book_value     DECIMAL(15,2) NOT NULL,
    current_book_value      DECIMAL(15,2) NOT NULL,
    calculation_status      VARCHAR(30) DEFAULT 'CALCULATED',
    depreciation_method     VARCHAR(30) DEFAULT 'STRAIGHT_LINE',
    observations            VARCHAR(1000),
    calculated_by           UUID,
    approved_by             UUID,
    calculation_date        TIMESTAMP DEFAULT NOW(),
    approval_date           TIMESTAMP,
    CONSTRAINT fk_depreciation_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT uk_depreciation_period UNIQUE (asset_id, fiscal_year, calculation_month),
    CONSTRAINT chk_month_valid CHECK (calculation_month BETWEEN 1 AND 12),
    CONSTRAINT chk_calculation_status CHECK (calculation_status IN ('CALCULATED', 'APPROVED', 'REJECTED', 'ADJUSTED')),
    CONSTRAINT chk_depreciation_method CHECK (depreciation_method IN ('STRAIGHT_LINE', 'ACCELERATED', 'UNITS_OF_PRODUCTION'))
);

CREATE TABLE IF NOT EXISTS asset_disposals (
    id                      UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    municipality_id         UUID NOT NULL,
    file_number             VARCHAR(50) UNIQUE NOT NULL,
    disposal_type           VARCHAR(30) NOT NULL,
    disposal_reason         VARCHAR(50) NOT NULL,
    reason_description      VARCHAR(1000) NOT NULL,
    request_date            DATE NOT NULL DEFAULT CURRENT_DATE,
    technical_evaluation_date DATE,
    resolution_date         DATE,
    physical_removal_date   DATE,
    technical_report_author_id UUID NOT NULL,
    technical_report        VARCHAR(5000),
    approved_by_id          UUID,
    approval_date           DATE,
    file_status             VARCHAR(30) DEFAULT 'INITIATED',
    resolution_number       VARCHAR(100),
    supporting_documents    VARCHAR(1000) DEFAULT '[]',
    observations            VARCHAR(1000),
    requires_destruction    BOOLEAN DEFAULT false,
    allows_donation         BOOLEAN DEFAULT false,
    recoverable_value       DECIMAL(15,2) DEFAULT 0,
    requested_by            UUID NOT NULL,
    created_at              TIMESTAMP DEFAULT NOW(),
    updated_by              UUID,
    updated_at              TIMESTAMP DEFAULT NOW(),
    CONSTRAINT chk_disposal_type CHECK (disposal_type IN ('ADMINISTRATIVE', 'TECHNICAL', 'FORTUITOUS', 'OBSOLESCENCE')),
    CONSTRAINT chk_file_status CHECK (file_status IN ('INITIATED', 'UNDER_EVALUATION', 'APPROVED', 'REJECTED', 'EXECUTED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS asset_disposal_detail (
    id                      UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    municipality_id         UUID NOT NULL,
    disposal_id             UUID NOT NULL,
    asset_id                UUID NOT NULL,
    conservation_status     VARCHAR(30) NOT NULL,
    book_value              DECIMAL(15,2) NOT NULL,
    recoverable_value       DECIMAL(15,2) DEFAULT 0,
    technical_opinion       VARCHAR(5000),
    recommendation          VARCHAR(50),
    removal_date            DATE,
    removal_responsible_id  UUID,
    final_destination       VARCHAR(100),
    observations            VARCHAR(1000),
    condition_photographs   VARCHAR(1000) DEFAULT '[]',
    created_at              TIMESTAMP DEFAULT NOW(),
    updated_at              TIMESTAMP DEFAULT NOW(),
    CONSTRAINT chk_recommendation CHECK (recommendation IN ('DESTROY', 'DONATE', 'SELL', 'RECYCLE', 'TRANSFER')),
    FOREIGN KEY (disposal_id) REFERENCES asset_disposals(id) ON DELETE CASCADE,
    FOREIGN KEY (asset_id) REFERENCES assets(id)
);
