spring:
  application:
    name: patrimonio-service-jmeter

  main:
    web-application-type: reactive
    lazy-initialization: false

  jmx:
    enabled: false

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/patrimonio_jmeter
    username: jmeter
    password: jmeter_pass
    pool:
      enabled: true
      initial-size: 2
      max-size: 5
      max-idle-time: 5m
      validation-query: SELECT 1
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

server:
  port: 5003
  error:
    include-message: always
    include-binding-errors: always

reactor:
  netty:
    io-worker-count: 4
    io-select-count: 2

logging:
  level:
    root: WARN
    pe.edu.vallegrande.patrimonio_service: DEBUG